FROM kong:3.5

USER root

# Install required tools and headers
RUN apt-get update && \
    apt-get install -y --no-install-recommends \
    build-essential \
    git \
    unzip \
    luarocks \
    libssl-dev && \
    rm -rf /var/lib/apt/lists/*

# Install luaossl (native binding to OpenSSL)
RUN luarocks install https://luarocks.org/luaossl-20220711-0.src.rock \
    CRYPTO_INCDIR=/usr/include \
    CRYPTO_LIBDIR=/usr/lib/x86_64-linux-gnu \
    OPENSSL_INCDIR=/usr/include \
    OPENSSL_LIBDIR=/usr/lib/x86_64-linux-gnu

# Install pure Lua dependencies (bypass manifest with rockspec URLs)
RUN luarocks install https://raw.githubusercontent.com/SkyLothar/lua-resty-jwt/master/lua-resty-jwt-0.2.0-1.rockspec && \
    luarocks install https://raw.githubusercontent.com/bungle/lua-resty-session/master/lua-resty-session-3.8-1.rockspec && \
    luarocks install https://raw.githubusercontent.com/zmartzone/lua-resty-openidc/master/lua-resty-openidc-1.7.4-1.rockspec

# Install kong-oidc plugin
RUN git clone --branch v1.2.3-2 https://github.com/revomatico/kong-oidc.git && \
    cd kong-oidc && luarocks make && cd .. && rm -rf kong-oidc

# Install jwt-keycloak plugin
RUN git clone --branch 20200505-access-token-processing https://github.com/BGaunitz/kong-plugin-jwt-keycloak.git && \
    cd kong-plugin-jwt-keycloak && luarocks make && cd .. && rm -rf kong-plugin-jwt-keycloak

# Optional: Add custom plugin (if needed)
COPY keycloak-introspection /usr/local/share/lua/5.1/kong/plugins/keycloak-introspection

# Copy Kong config
COPY config/kong.conf /etc/kong/kong.conf

USER kong
