// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.21.12
// source: communication.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// ExampleGreeterClient is the client API for ExampleGreeter service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ExampleGreeterClient interface {
	// Sends a greeting
	SayHello(ctx context.Context, in *HelloRequest, opts ...grpc.CallOption) (*HelloReply, error)
}

type exampleGreeterClient struct {
	cc grpc.ClientConnInterface
}

func NewExampleGreeterClient(cc grpc.ClientConnInterface) ExampleGreeterClient {
	return &exampleGreeterClient{cc}
}

func (c *exampleGreeterClient) SayHello(ctx context.Context, in *HelloRequest, opts ...grpc.CallOption) (*HelloReply, error) {
	out := new(HelloReply)
	err := c.cc.Invoke(ctx, "/apiservice_proto.ExampleGreeter/SayHello", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ExampleGreeterServer is the server API for ExampleGreeter service.
// All implementations must embed UnimplementedExampleGreeterServer
// for forward compatibility
type ExampleGreeterServer interface {
	// Sends a greeting
	SayHello(context.Context, *HelloRequest) (*HelloReply, error)
	mustEmbedUnimplementedExampleGreeterServer()
}

// UnimplementedExampleGreeterServer must be embedded to have forward compatible implementations.
type UnimplementedExampleGreeterServer struct {
}

func (UnimplementedExampleGreeterServer) SayHello(context.Context, *HelloRequest) (*HelloReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SayHello not implemented")
}
func (UnimplementedExampleGreeterServer) mustEmbedUnimplementedExampleGreeterServer() {}

// UnsafeExampleGreeterServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ExampleGreeterServer will
// result in compilation errors.
type UnsafeExampleGreeterServer interface {
	mustEmbedUnimplementedExampleGreeterServer()
}

func RegisterExampleGreeterServer(s grpc.ServiceRegistrar, srv ExampleGreeterServer) {
	s.RegisterService(&ExampleGreeter_ServiceDesc, srv)
}

func _ExampleGreeter_SayHello_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HelloRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ExampleGreeterServer).SayHello(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/apiservice_proto.ExampleGreeter/SayHello",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ExampleGreeterServer).SayHello(ctx, req.(*HelloRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ExampleGreeter_ServiceDesc is the grpc.ServiceDesc for ExampleGreeter service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ExampleGreeter_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "apiservice_proto.ExampleGreeter",
	HandlerType: (*ExampleGreeterServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SayHello",
			Handler:    _ExampleGreeter_SayHello_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "communication.proto",
}

// MapsClient is the client API for Maps service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type MapsClient interface {
	Geocode(ctx context.Context, in *GeocodeRequest, opts ...grpc.CallOption) (*GeocodeResponse, error)
	SearchPlaces(ctx context.Context, in *SearchPlacesRequest, opts ...grpc.CallOption) (*SearchPlacesResponse, error)
	GetPlaceDetails(ctx context.Context, in *PlaceDetailsRequest, opts ...grpc.CallOption) (*PlaceDetailsResponse, error)
	GetDirections(ctx context.Context, in *DirectionsRequest, opts ...grpc.CallOption) (*DirectionsResponse, error)
	GetDistanceMatrix(ctx context.Context, in *DistanceMatrixRequest, opts ...grpc.CallOption) (*DistanceMatrixResponse, error)
}

type mapsClient struct {
	cc grpc.ClientConnInterface
}

func NewMapsClient(cc grpc.ClientConnInterface) MapsClient {
	return &mapsClient{cc}
}

func (c *mapsClient) Geocode(ctx context.Context, in *GeocodeRequest, opts ...grpc.CallOption) (*GeocodeResponse, error) {
	out := new(GeocodeResponse)
	err := c.cc.Invoke(ctx, "/apiservice_proto.Maps/Geocode", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mapsClient) SearchPlaces(ctx context.Context, in *SearchPlacesRequest, opts ...grpc.CallOption) (*SearchPlacesResponse, error) {
	out := new(SearchPlacesResponse)
	err := c.cc.Invoke(ctx, "/apiservice_proto.Maps/SearchPlaces", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mapsClient) GetPlaceDetails(ctx context.Context, in *PlaceDetailsRequest, opts ...grpc.CallOption) (*PlaceDetailsResponse, error) {
	out := new(PlaceDetailsResponse)
	err := c.cc.Invoke(ctx, "/apiservice_proto.Maps/GetPlaceDetails", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mapsClient) GetDirections(ctx context.Context, in *DirectionsRequest, opts ...grpc.CallOption) (*DirectionsResponse, error) {
	out := new(DirectionsResponse)
	err := c.cc.Invoke(ctx, "/apiservice_proto.Maps/GetDirections", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mapsClient) GetDistanceMatrix(ctx context.Context, in *DistanceMatrixRequest, opts ...grpc.CallOption) (*DistanceMatrixResponse, error) {
	out := new(DistanceMatrixResponse)
	err := c.cc.Invoke(ctx, "/apiservice_proto.Maps/GetDistanceMatrix", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MapsServer is the server API for Maps service.
// All implementations must embed UnimplementedMapsServer
// for forward compatibility
type MapsServer interface {
	Geocode(context.Context, *GeocodeRequest) (*GeocodeResponse, error)
	SearchPlaces(context.Context, *SearchPlacesRequest) (*SearchPlacesResponse, error)
	GetPlaceDetails(context.Context, *PlaceDetailsRequest) (*PlaceDetailsResponse, error)
	GetDirections(context.Context, *DirectionsRequest) (*DirectionsResponse, error)
	GetDistanceMatrix(context.Context, *DistanceMatrixRequest) (*DistanceMatrixResponse, error)
	mustEmbedUnimplementedMapsServer()
}

// UnimplementedMapsServer must be embedded to have forward compatible implementations.
type UnimplementedMapsServer struct {
}

func (UnimplementedMapsServer) Geocode(context.Context, *GeocodeRequest) (*GeocodeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Geocode not implemented")
}
func (UnimplementedMapsServer) SearchPlaces(context.Context, *SearchPlacesRequest) (*SearchPlacesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SearchPlaces not implemented")
}
func (UnimplementedMapsServer) GetPlaceDetails(context.Context, *PlaceDetailsRequest) (*PlaceDetailsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetPlaceDetails not implemented")
}
func (UnimplementedMapsServer) GetDirections(context.Context, *DirectionsRequest) (*DirectionsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetDirections not implemented")
}
func (UnimplementedMapsServer) GetDistanceMatrix(context.Context, *DistanceMatrixRequest) (*DistanceMatrixResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetDistanceMatrix not implemented")
}
func (UnimplementedMapsServer) mustEmbedUnimplementedMapsServer() {}

// UnsafeMapsServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MapsServer will
// result in compilation errors.
type UnsafeMapsServer interface {
	mustEmbedUnimplementedMapsServer()
}

func RegisterMapsServer(s grpc.ServiceRegistrar, srv MapsServer) {
	s.RegisterService(&Maps_ServiceDesc, srv)
}

func _Maps_Geocode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GeocodeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MapsServer).Geocode(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/apiservice_proto.Maps/Geocode",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MapsServer).Geocode(ctx, req.(*GeocodeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Maps_SearchPlaces_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SearchPlacesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MapsServer).SearchPlaces(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/apiservice_proto.Maps/SearchPlaces",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MapsServer).SearchPlaces(ctx, req.(*SearchPlacesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Maps_GetPlaceDetails_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PlaceDetailsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MapsServer).GetPlaceDetails(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/apiservice_proto.Maps/GetPlaceDetails",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MapsServer).GetPlaceDetails(ctx, req.(*PlaceDetailsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Maps_GetDirections_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DirectionsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MapsServer).GetDirections(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/apiservice_proto.Maps/GetDirections",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MapsServer).GetDirections(ctx, req.(*DirectionsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Maps_GetDistanceMatrix_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DistanceMatrixRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MapsServer).GetDistanceMatrix(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/apiservice_proto.Maps/GetDistanceMatrix",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MapsServer).GetDistanceMatrix(ctx, req.(*DistanceMatrixRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Maps_ServiceDesc is the grpc.ServiceDesc for Maps service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Maps_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "apiservice_proto.Maps",
	HandlerType: (*MapsServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Geocode",
			Handler:    _Maps_Geocode_Handler,
		},
		{
			MethodName: "SearchPlaces",
			Handler:    _Maps_SearchPlaces_Handler,
		},
		{
			MethodName: "GetPlaceDetails",
			Handler:    _Maps_GetPlaceDetails_Handler,
		},
		{
			MethodName: "GetDirections",
			Handler:    _Maps_GetDirections_Handler,
		},
		{
			MethodName: "GetDistanceMatrix",
			Handler:    _Maps_GetDistanceMatrix_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "communication.proto",
}

// GeminiClient is the client API for Gemini service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type GeminiClient interface {
	GenerateContent(ctx context.Context, in *GeminiRequest, opts ...grpc.CallOption) (*GeminiResponse, error)
}

type geminiClient struct {
	cc grpc.ClientConnInterface
}

func NewGeminiClient(cc grpc.ClientConnInterface) GeminiClient {
	return &geminiClient{cc}
}

func (c *geminiClient) GenerateContent(ctx context.Context, in *GeminiRequest, opts ...grpc.CallOption) (*GeminiResponse, error) {
	out := new(GeminiResponse)
	err := c.cc.Invoke(ctx, "/apiservice_proto.Gemini/GenerateContent", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GeminiServer is the server API for Gemini service.
// All implementations must embed UnimplementedGeminiServer
// for forward compatibility
type GeminiServer interface {
	GenerateContent(context.Context, *GeminiRequest) (*GeminiResponse, error)
	mustEmbedUnimplementedGeminiServer()
}

// UnimplementedGeminiServer must be embedded to have forward compatible implementations.
type UnimplementedGeminiServer struct {
}

func (UnimplementedGeminiServer) GenerateContent(context.Context, *GeminiRequest) (*GeminiResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GenerateContent not implemented")
}
func (UnimplementedGeminiServer) mustEmbedUnimplementedGeminiServer() {}

// UnsafeGeminiServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to GeminiServer will
// result in compilation errors.
type UnsafeGeminiServer interface {
	mustEmbedUnimplementedGeminiServer()
}

func RegisterGeminiServer(s grpc.ServiceRegistrar, srv GeminiServer) {
	s.RegisterService(&Gemini_ServiceDesc, srv)
}

func _Gemini_GenerateContent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GeminiRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GeminiServer).GenerateContent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/apiservice_proto.Gemini/GenerateContent",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GeminiServer).GenerateContent(ctx, req.(*GeminiRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Gemini_ServiceDesc is the grpc.ServiceDesc for Gemini service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Gemini_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "apiservice_proto.Gemini",
	HandlerType: (*GeminiServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GenerateContent",
			Handler:    _Gemini_GenerateContent_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "communication.proto",
}
