# config/kong.conf
database = postgres
pg_host = kong-database
pg_user = kong
pg_password = mykongpassword
pg_database = kong

plugins = bundled,keycloak-introspection

admin_listen = 0.0.0.0:8001
proxy_listen = 0.0.0.0:8000, 0.0.0.0:8443 ssl

client_id = kong-oidc
client_secret = xxxxxxxx
realm = kong
discovery = http://keycloak:8080/realms/kong/.well-known/openid-configuration
scope = openid
redirect_after_logout_uri = https://localhost/auth/realms/kong/protocol/openid-connect/logout?redirect_uri=https://localhost