FROM kong:3.5

USER root

RUN apt-get update && \
    apt-get install -y --no-install-recommends \
    git \
    unzip \
    luarocks && \
    rm -rf /var/lib/apt/lists/*

# Install kong-oidc plugin
RUN git clone --branch v1.2.3-2 https://github.com/revomatico/kong-oidc.git \
 && cd kong-oidc && luarocks make

# Install kong-plugin-jwt-keycloak plugin
RUN git clone --branch 20200505-access-token-processing https://github.com/BGaunitz/kong-plugin-jwt-keycloak.git \
 && cd kong-plugin-jwt-keycloak && luarocks make

 COPY keycloak-introspection /usr/local/share/lua/5.1/kong/plugins/keycloak-introspection

 # Add this at the end before USER kong
COPY config/kong.conf /etc/kong/kong.conf

USER kong
