spring.application.name=post-service

# Database configuration - Credentials should be externalized
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://aws-0-ap-southeast-1.pooler.supabase.com:5432/postgres?user=postgres.odffpjvuptssxaaggnsn&password=Postgres
#spring.jpa.hibernate.ddl-auto=none
spring.datasource.username=${DB_USER:postgres.odffpjvuptssxaaggnsn}
spring.datasource.password=${DB_PASSWORD:Postgres} 
# Externalize this!

# JPA & Hibernate Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true

logging.level.org.springframework.web.cors=DEBUG

