spring.application.name=planning-service
server.port=8081

# API Service gRPC Endpoint
api.service.host=localhost
api.service.port=50051

social-media-service.url=http://localhost:8080
social-media-service.trip-history-path=/api/trips/history/