spring.application.name=user-service

# Database configuration
#spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=postgres.odffpjvuptssxaaggnsn
spring.datasource.password=Postgres

#spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
#spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}

spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://aws-0-ap-southeast-1.pooler.supabase.com:5432/postgres?user=postgres.odffpjvuptssxaaggnsn&password=Postgres
#spring.jpa.hibernate.ddl-auto=none

# JPA & Hibernate Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true

logging.level.org.springframework.web.cors=DEBUG
