// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.21.12
// source: maps.proto

package maps

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// --- Geocoding ---
type GeocodeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Address       string                 `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GeocodeRequest) Reset() {
	*x = GeocodeRequest{}
	mi := &file_maps_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GeocodeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GeocodeRequest) ProtoMessage() {}

func (x *GeocodeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_maps_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GeocodeRequest.ProtoReflect.Descriptor instead.
func (*GeocodeRequest) Descriptor() ([]byte, []int) {
	return file_maps_proto_rawDescGZIP(), []int{0}
}

func (x *GeocodeRequest) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

type GeocodeResponse struct {
	state         protoimpl.MessageState    `protogen:"open.v1"`
	Results       []*GeocodeResponse_Result `protobuf:"bytes,1,rep,name=results,proto3" json:"results,omitempty"`
	Status        string                    `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GeocodeResponse) Reset() {
	*x = GeocodeResponse{}
	mi := &file_maps_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GeocodeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GeocodeResponse) ProtoMessage() {}

func (x *GeocodeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_maps_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GeocodeResponse.ProtoReflect.Descriptor instead.
func (*GeocodeResponse) Descriptor() ([]byte, []int) {
	return file_maps_proto_rawDescGZIP(), []int{1}
}

func (x *GeocodeResponse) GetResults() []*GeocodeResponse_Result {
	if x != nil {
		return x.Results
	}
	return nil
}

func (x *GeocodeResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

// --- Places Search ---
type SearchPlacesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Query         string                 `protobuf:"bytes,1,opt,name=query,proto3" json:"query,omitempty"`
	Location      string                 `protobuf:"bytes,2,opt,name=location,proto3" json:"location,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchPlacesRequest) Reset() {
	*x = SearchPlacesRequest{}
	mi := &file_maps_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchPlacesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchPlacesRequest) ProtoMessage() {}

func (x *SearchPlacesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_maps_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchPlacesRequest.ProtoReflect.Descriptor instead.
func (*SearchPlacesRequest) Descriptor() ([]byte, []int) {
	return file_maps_proto_rawDescGZIP(), []int{2}
}

func (x *SearchPlacesRequest) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

func (x *SearchPlacesRequest) GetLocation() string {
	if x != nil {
		return x.Location
	}
	return ""
}

type Place struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	PlaceId          string                 `protobuf:"bytes,1,opt,name=place_id,json=placeId,proto3" json:"place_id,omitempty"`
	Name             string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Vicinity         string                 `protobuf:"bytes,3,opt,name=vicinity,proto3" json:"vicinity,omitempty"`
	Rating           float64                `protobuf:"fixed64,4,opt,name=rating,proto3" json:"rating,omitempty"`
	UserRatingsTotal int32                  `protobuf:"varint,5,opt,name=user_ratings_total,json=userRatingsTotal,proto3" json:"user_ratings_total,omitempty"`
	GeometryLocation *Place_Location        `protobuf:"bytes,6,opt,name=geometry_location,json=geometryLocation,proto3" json:"geometry_location,omitempty"`
	OpeningHours     *Place_OpeningHours    `protobuf:"bytes,7,opt,name=opening_hours,json=openingHours,proto3" json:"opening_hours,omitempty"`
	Photos           []*Place_Photo         `protobuf:"bytes,8,rep,name=photos,proto3" json:"photos,omitempty"`
	PhotoUrls        []string               `protobuf:"bytes,9,rep,name=photo_urls,json=photoUrls,proto3" json:"photo_urls,omitempty"`
	Types            []string               `protobuf:"bytes,10,rep,name=types,proto3" json:"types,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *Place) Reset() {
	*x = Place{}
	mi := &file_maps_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Place) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Place) ProtoMessage() {}

func (x *Place) ProtoReflect() protoreflect.Message {
	mi := &file_maps_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Place.ProtoReflect.Descriptor instead.
func (*Place) Descriptor() ([]byte, []int) {
	return file_maps_proto_rawDescGZIP(), []int{3}
}

func (x *Place) GetPlaceId() string {
	if x != nil {
		return x.PlaceId
	}
	return ""
}

func (x *Place) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Place) GetVicinity() string {
	if x != nil {
		return x.Vicinity
	}
	return ""
}

func (x *Place) GetRating() float64 {
	if x != nil {
		return x.Rating
	}
	return 0
}

func (x *Place) GetUserRatingsTotal() int32 {
	if x != nil {
		return x.UserRatingsTotal
	}
	return 0
}

func (x *Place) GetGeometryLocation() *Place_Location {
	if x != nil {
		return x.GeometryLocation
	}
	return nil
}

func (x *Place) GetOpeningHours() *Place_OpeningHours {
	if x != nil {
		return x.OpeningHours
	}
	return nil
}

func (x *Place) GetPhotos() []*Place_Photo {
	if x != nil {
		return x.Photos
	}
	return nil
}

func (x *Place) GetPhotoUrls() []string {
	if x != nil {
		return x.PhotoUrls
	}
	return nil
}

func (x *Place) GetTypes() []string {
	if x != nil {
		return x.Types
	}
	return nil
}

type SearchPlacesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Results       []*Place               `protobuf:"bytes,1,rep,name=results,proto3" json:"results,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchPlacesResponse) Reset() {
	*x = SearchPlacesResponse{}
	mi := &file_maps_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchPlacesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchPlacesResponse) ProtoMessage() {}

func (x *SearchPlacesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_maps_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchPlacesResponse.ProtoReflect.Descriptor instead.
func (*SearchPlacesResponse) Descriptor() ([]byte, []int) {
	return file_maps_proto_rawDescGZIP(), []int{4}
}

func (x *SearchPlacesResponse) GetResults() []*Place {
	if x != nil {
		return x.Results
	}
	return nil
}

func (x *SearchPlacesResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

// --- Place Details ---
type PlaceDetailsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PlaceId       string                 `protobuf:"bytes,1,opt,name=place_id,json=placeId,proto3" json:"place_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlaceDetailsRequest) Reset() {
	*x = PlaceDetailsRequest{}
	mi := &file_maps_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlaceDetailsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlaceDetailsRequest) ProtoMessage() {}

func (x *PlaceDetailsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_maps_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlaceDetailsRequest.ProtoReflect.Descriptor instead.
func (*PlaceDetailsRequest) Descriptor() ([]byte, []int) {
	return file_maps_proto_rawDescGZIP(), []int{5}
}

func (x *PlaceDetailsRequest) GetPlaceId() string {
	if x != nil {
		return x.PlaceId
	}
	return ""
}

type PlaceDetailsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Result        *Place                 `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlaceDetailsResponse) Reset() {
	*x = PlaceDetailsResponse{}
	mi := &file_maps_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlaceDetailsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlaceDetailsResponse) ProtoMessage() {}

func (x *PlaceDetailsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_maps_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlaceDetailsResponse.ProtoReflect.Descriptor instead.
func (*PlaceDetailsResponse) Descriptor() ([]byte, []int) {
	return file_maps_proto_rawDescGZIP(), []int{6}
}

func (x *PlaceDetailsResponse) GetResult() *Place {
	if x != nil {
		return x.Result
	}
	return nil
}

func (x *PlaceDetailsResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

// --- Directions ---
type DirectionsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Origin        string                 `protobuf:"bytes,1,opt,name=origin,proto3" json:"origin,omitempty"`
	Destination   string                 `protobuf:"bytes,2,opt,name=destination,proto3" json:"destination,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DirectionsRequest) Reset() {
	*x = DirectionsRequest{}
	mi := &file_maps_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DirectionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DirectionsRequest) ProtoMessage() {}

func (x *DirectionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_maps_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DirectionsRequest.ProtoReflect.Descriptor instead.
func (*DirectionsRequest) Descriptor() ([]byte, []int) {
	return file_maps_proto_rawDescGZIP(), []int{7}
}

func (x *DirectionsRequest) GetOrigin() string {
	if x != nil {
		return x.Origin
	}
	return ""
}

func (x *DirectionsRequest) GetDestination() string {
	if x != nil {
		return x.Destination
	}
	return ""
}

type DirectionsResponse struct {
	state             protoimpl.MessageState                 `protogen:"open.v1"`
	Routes            []*DirectionsResponse_Route            `protobuf:"bytes,1,rep,name=routes,proto3" json:"routes,omitempty"`
	GeocodedWaypoints []*DirectionsResponse_GeocodedWaypoint `protobuf:"bytes,2,rep,name=geocoded_waypoints,json=geocodedWaypoints,proto3" json:"geocoded_waypoints,omitempty"`
	Status            string                                 `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *DirectionsResponse) Reset() {
	*x = DirectionsResponse{}
	mi := &file_maps_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DirectionsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DirectionsResponse) ProtoMessage() {}

func (x *DirectionsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_maps_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DirectionsResponse.ProtoReflect.Descriptor instead.
func (*DirectionsResponse) Descriptor() ([]byte, []int) {
	return file_maps_proto_rawDescGZIP(), []int{8}
}

func (x *DirectionsResponse) GetRoutes() []*DirectionsResponse_Route {
	if x != nil {
		return x.Routes
	}
	return nil
}

func (x *DirectionsResponse) GetGeocodedWaypoints() []*DirectionsResponse_GeocodedWaypoint {
	if x != nil {
		return x.GeocodedWaypoints
	}
	return nil
}

func (x *DirectionsResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

// --- Distance Matrix ---
type DistanceMatrixRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Origins       string                 `protobuf:"bytes,1,opt,name=origins,proto3" json:"origins,omitempty"`
	Destinations  string                 `protobuf:"bytes,2,opt,name=destinations,proto3" json:"destinations,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DistanceMatrixRequest) Reset() {
	*x = DistanceMatrixRequest{}
	mi := &file_maps_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DistanceMatrixRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DistanceMatrixRequest) ProtoMessage() {}

func (x *DistanceMatrixRequest) ProtoReflect() protoreflect.Message {
	mi := &file_maps_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DistanceMatrixRequest.ProtoReflect.Descriptor instead.
func (*DistanceMatrixRequest) Descriptor() ([]byte, []int) {
	return file_maps_proto_rawDescGZIP(), []int{9}
}

func (x *DistanceMatrixRequest) GetOrigins() string {
	if x != nil {
		return x.Origins
	}
	return ""
}

func (x *DistanceMatrixRequest) GetDestinations() string {
	if x != nil {
		return x.Destinations
	}
	return ""
}

type DistanceMatrixResponse struct {
	state                protoimpl.MessageState        `protogen:"open.v1"`
	OriginAddresses      []string                      `protobuf:"bytes,1,rep,name=origin_addresses,json=originAddresses,proto3" json:"origin_addresses,omitempty"`
	DestinationAddresses []string                      `protobuf:"bytes,2,rep,name=destination_addresses,json=destinationAddresses,proto3" json:"destination_addresses,omitempty"`
	Rows                 []*DistanceMatrixResponse_Row `protobuf:"bytes,3,rep,name=rows,proto3" json:"rows,omitempty"`
	Status               string                        `protobuf:"bytes,4,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *DistanceMatrixResponse) Reset() {
	*x = DistanceMatrixResponse{}
	mi := &file_maps_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DistanceMatrixResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DistanceMatrixResponse) ProtoMessage() {}

func (x *DistanceMatrixResponse) ProtoReflect() protoreflect.Message {
	mi := &file_maps_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DistanceMatrixResponse.ProtoReflect.Descriptor instead.
func (*DistanceMatrixResponse) Descriptor() ([]byte, []int) {
	return file_maps_proto_rawDescGZIP(), []int{10}
}

func (x *DistanceMatrixResponse) GetOriginAddresses() []string {
	if x != nil {
		return x.OriginAddresses
	}
	return nil
}

func (x *DistanceMatrixResponse) GetDestinationAddresses() []string {
	if x != nil {
		return x.DestinationAddresses
	}
	return nil
}

func (x *DistanceMatrixResponse) GetRows() []*DistanceMatrixResponse_Row {
	if x != nil {
		return x.Rows
	}
	return nil
}

func (x *DistanceMatrixResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type GeocodeResponse_Location struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Lat           float64                `protobuf:"fixed64,1,opt,name=lat,proto3" json:"lat,omitempty"`
	Lng           float64                `protobuf:"fixed64,2,opt,name=lng,proto3" json:"lng,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GeocodeResponse_Location) Reset() {
	*x = GeocodeResponse_Location{}
	mi := &file_maps_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GeocodeResponse_Location) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GeocodeResponse_Location) ProtoMessage() {}

func (x *GeocodeResponse_Location) ProtoReflect() protoreflect.Message {
	mi := &file_maps_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GeocodeResponse_Location.ProtoReflect.Descriptor instead.
func (*GeocodeResponse_Location) Descriptor() ([]byte, []int) {
	return file_maps_proto_rawDescGZIP(), []int{1, 0}
}

func (x *GeocodeResponse_Location) GetLat() float64 {
	if x != nil {
		return x.Lat
	}
	return 0
}

func (x *GeocodeResponse_Location) GetLng() float64 {
	if x != nil {
		return x.Lng
	}
	return 0
}

type GeocodeResponse_Result struct {
	state            protoimpl.MessageState    `protogen:"open.v1"`
	FormattedAddress string                    `protobuf:"bytes,1,opt,name=formatted_address,json=formattedAddress,proto3" json:"formatted_address,omitempty"`
	Location         *GeocodeResponse_Location `protobuf:"bytes,2,opt,name=location,proto3" json:"location,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *GeocodeResponse_Result) Reset() {
	*x = GeocodeResponse_Result{}
	mi := &file_maps_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GeocodeResponse_Result) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GeocodeResponse_Result) ProtoMessage() {}

func (x *GeocodeResponse_Result) ProtoReflect() protoreflect.Message {
	mi := &file_maps_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GeocodeResponse_Result.ProtoReflect.Descriptor instead.
func (*GeocodeResponse_Result) Descriptor() ([]byte, []int) {
	return file_maps_proto_rawDescGZIP(), []int{1, 1}
}

func (x *GeocodeResponse_Result) GetFormattedAddress() string {
	if x != nil {
		return x.FormattedAddress
	}
	return ""
}

func (x *GeocodeResponse_Result) GetLocation() *GeocodeResponse_Location {
	if x != nil {
		return x.Location
	}
	return nil
}

type Place_Location struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Lat           float64                `protobuf:"fixed64,1,opt,name=lat,proto3" json:"lat,omitempty"`
	Lng           float64                `protobuf:"fixed64,2,opt,name=lng,proto3" json:"lng,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Place_Location) Reset() {
	*x = Place_Location{}
	mi := &file_maps_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Place_Location) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Place_Location) ProtoMessage() {}

func (x *Place_Location) ProtoReflect() protoreflect.Message {
	mi := &file_maps_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Place_Location.ProtoReflect.Descriptor instead.
func (*Place_Location) Descriptor() ([]byte, []int) {
	return file_maps_proto_rawDescGZIP(), []int{3, 0}
}

func (x *Place_Location) GetLat() float64 {
	if x != nil {
		return x.Lat
	}
	return 0
}

func (x *Place_Location) GetLng() float64 {
	if x != nil {
		return x.Lng
	}
	return 0
}

type Place_OpeningHours struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OpenNow       bool                   `protobuf:"varint,1,opt,name=open_now,json=openNow,proto3" json:"open_now,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Place_OpeningHours) Reset() {
	*x = Place_OpeningHours{}
	mi := &file_maps_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Place_OpeningHours) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Place_OpeningHours) ProtoMessage() {}

func (x *Place_OpeningHours) ProtoReflect() protoreflect.Message {
	mi := &file_maps_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Place_OpeningHours.ProtoReflect.Descriptor instead.
func (*Place_OpeningHours) Descriptor() ([]byte, []int) {
	return file_maps_proto_rawDescGZIP(), []int{3, 1}
}

func (x *Place_OpeningHours) GetOpenNow() bool {
	if x != nil {
		return x.OpenNow
	}
	return false
}

type Place_Photo struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	PhotoReference string                 `protobuf:"bytes,1,opt,name=photo_reference,json=photoReference,proto3" json:"photo_reference,omitempty"`
	Height         int32                  `protobuf:"varint,2,opt,name=height,proto3" json:"height,omitempty"`
	Width          int32                  `protobuf:"varint,3,opt,name=width,proto3" json:"width,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Place_Photo) Reset() {
	*x = Place_Photo{}
	mi := &file_maps_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Place_Photo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Place_Photo) ProtoMessage() {}

func (x *Place_Photo) ProtoReflect() protoreflect.Message {
	mi := &file_maps_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Place_Photo.ProtoReflect.Descriptor instead.
func (*Place_Photo) Descriptor() ([]byte, []int) {
	return file_maps_proto_rawDescGZIP(), []int{3, 2}
}

func (x *Place_Photo) GetPhotoReference() string {
	if x != nil {
		return x.PhotoReference
	}
	return ""
}

func (x *Place_Photo) GetHeight() int32 {
	if x != nil {
		return x.Height
	}
	return 0
}

func (x *Place_Photo) GetWidth() int32 {
	if x != nil {
		return x.Width
	}
	return 0
}

type DirectionsResponse_Distance struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Text          string                 `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`
	Value         int32                  `protobuf:"varint,2,opt,name=value,proto3" json:"value,omitempty"` // meters
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DirectionsResponse_Distance) Reset() {
	*x = DirectionsResponse_Distance{}
	mi := &file_maps_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DirectionsResponse_Distance) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DirectionsResponse_Distance) ProtoMessage() {}

func (x *DirectionsResponse_Distance) ProtoReflect() protoreflect.Message {
	mi := &file_maps_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DirectionsResponse_Distance.ProtoReflect.Descriptor instead.
func (*DirectionsResponse_Distance) Descriptor() ([]byte, []int) {
	return file_maps_proto_rawDescGZIP(), []int{8, 0}
}

func (x *DirectionsResponse_Distance) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *DirectionsResponse_Distance) GetValue() int32 {
	if x != nil {
		return x.Value
	}
	return 0
}

type DirectionsResponse_Duration struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Text          string                 `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`
	Value         int32                  `protobuf:"varint,2,opt,name=value,proto3" json:"value,omitempty"` // seconds
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DirectionsResponse_Duration) Reset() {
	*x = DirectionsResponse_Duration{}
	mi := &file_maps_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DirectionsResponse_Duration) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DirectionsResponse_Duration) ProtoMessage() {}

func (x *DirectionsResponse_Duration) ProtoReflect() protoreflect.Message {
	mi := &file_maps_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DirectionsResponse_Duration.ProtoReflect.Descriptor instead.
func (*DirectionsResponse_Duration) Descriptor() ([]byte, []int) {
	return file_maps_proto_rawDescGZIP(), []int{8, 1}
}

func (x *DirectionsResponse_Duration) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *DirectionsResponse_Duration) GetValue() int32 {
	if x != nil {
		return x.Value
	}
	return 0
}

type DirectionsResponse_Polyline struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Points        string                 `protobuf:"bytes,1,opt,name=points,proto3" json:"points,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DirectionsResponse_Polyline) Reset() {
	*x = DirectionsResponse_Polyline{}
	mi := &file_maps_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DirectionsResponse_Polyline) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DirectionsResponse_Polyline) ProtoMessage() {}

func (x *DirectionsResponse_Polyline) ProtoReflect() protoreflect.Message {
	mi := &file_maps_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DirectionsResponse_Polyline.ProtoReflect.Descriptor instead.
func (*DirectionsResponse_Polyline) Descriptor() ([]byte, []int) {
	return file_maps_proto_rawDescGZIP(), []int{8, 2}
}

func (x *DirectionsResponse_Polyline) GetPoints() string {
	if x != nil {
		return x.Points
	}
	return ""
}

type DirectionsResponse_Step struct {
	state            protoimpl.MessageState       `protogen:"open.v1"`
	HtmlInstructions string                       `protobuf:"bytes,1,opt,name=html_instructions,json=htmlInstructions,proto3" json:"html_instructions,omitempty"`
	Distance         *DirectionsResponse_Distance `protobuf:"bytes,2,opt,name=distance,proto3" json:"distance,omitempty"`
	Duration         *DirectionsResponse_Duration `protobuf:"bytes,3,opt,name=duration,proto3" json:"duration,omitempty"`
	Polyline         *DirectionsResponse_Polyline `protobuf:"bytes,4,opt,name=polyline,proto3" json:"polyline,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *DirectionsResponse_Step) Reset() {
	*x = DirectionsResponse_Step{}
	mi := &file_maps_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DirectionsResponse_Step) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DirectionsResponse_Step) ProtoMessage() {}

func (x *DirectionsResponse_Step) ProtoReflect() protoreflect.Message {
	mi := &file_maps_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DirectionsResponse_Step.ProtoReflect.Descriptor instead.
func (*DirectionsResponse_Step) Descriptor() ([]byte, []int) {
	return file_maps_proto_rawDescGZIP(), []int{8, 3}
}

func (x *DirectionsResponse_Step) GetHtmlInstructions() string {
	if x != nil {
		return x.HtmlInstructions
	}
	return ""
}

func (x *DirectionsResponse_Step) GetDistance() *DirectionsResponse_Distance {
	if x != nil {
		return x.Distance
	}
	return nil
}

func (x *DirectionsResponse_Step) GetDuration() *DirectionsResponse_Duration {
	if x != nil {
		return x.Duration
	}
	return nil
}

func (x *DirectionsResponse_Step) GetPolyline() *DirectionsResponse_Polyline {
	if x != nil {
		return x.Polyline
	}
	return nil
}

type DirectionsResponse_Leg struct {
	state         protoimpl.MessageState       `protogen:"open.v1"`
	Distance      *DirectionsResponse_Distance `protobuf:"bytes,1,opt,name=distance,proto3" json:"distance,omitempty"`
	Duration      *DirectionsResponse_Duration `protobuf:"bytes,2,opt,name=duration,proto3" json:"duration,omitempty"`
	StartAddress  string                       `protobuf:"bytes,3,opt,name=start_address,json=startAddress,proto3" json:"start_address,omitempty"`
	EndAddress    string                       `protobuf:"bytes,4,opt,name=end_address,json=endAddress,proto3" json:"end_address,omitempty"`
	Steps         []*DirectionsResponse_Step   `protobuf:"bytes,5,rep,name=steps,proto3" json:"steps,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DirectionsResponse_Leg) Reset() {
	*x = DirectionsResponse_Leg{}
	mi := &file_maps_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DirectionsResponse_Leg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DirectionsResponse_Leg) ProtoMessage() {}

func (x *DirectionsResponse_Leg) ProtoReflect() protoreflect.Message {
	mi := &file_maps_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DirectionsResponse_Leg.ProtoReflect.Descriptor instead.
func (*DirectionsResponse_Leg) Descriptor() ([]byte, []int) {
	return file_maps_proto_rawDescGZIP(), []int{8, 4}
}

func (x *DirectionsResponse_Leg) GetDistance() *DirectionsResponse_Distance {
	if x != nil {
		return x.Distance
	}
	return nil
}

func (x *DirectionsResponse_Leg) GetDuration() *DirectionsResponse_Duration {
	if x != nil {
		return x.Duration
	}
	return nil
}

func (x *DirectionsResponse_Leg) GetStartAddress() string {
	if x != nil {
		return x.StartAddress
	}
	return ""
}

func (x *DirectionsResponse_Leg) GetEndAddress() string {
	if x != nil {
		return x.EndAddress
	}
	return ""
}

func (x *DirectionsResponse_Leg) GetSteps() []*DirectionsResponse_Step {
	if x != nil {
		return x.Steps
	}
	return nil
}

type DirectionsResponse_Route struct {
	state            protoimpl.MessageState       `protogen:"open.v1"`
	Summary          string                       `protobuf:"bytes,1,opt,name=summary,proto3" json:"summary,omitempty"`
	Legs             []*DirectionsResponse_Leg    `protobuf:"bytes,2,rep,name=legs,proto3" json:"legs,omitempty"`
	OverviewPolyline *DirectionsResponse_Polyline `protobuf:"bytes,3,opt,name=overview_polyline,json=overviewPolyline,proto3" json:"overview_polyline,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *DirectionsResponse_Route) Reset() {
	*x = DirectionsResponse_Route{}
	mi := &file_maps_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DirectionsResponse_Route) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DirectionsResponse_Route) ProtoMessage() {}

func (x *DirectionsResponse_Route) ProtoReflect() protoreflect.Message {
	mi := &file_maps_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DirectionsResponse_Route.ProtoReflect.Descriptor instead.
func (*DirectionsResponse_Route) Descriptor() ([]byte, []int) {
	return file_maps_proto_rawDescGZIP(), []int{8, 5}
}

func (x *DirectionsResponse_Route) GetSummary() string {
	if x != nil {
		return x.Summary
	}
	return ""
}

func (x *DirectionsResponse_Route) GetLegs() []*DirectionsResponse_Leg {
	if x != nil {
		return x.Legs
	}
	return nil
}

func (x *DirectionsResponse_Route) GetOverviewPolyline() *DirectionsResponse_Polyline {
	if x != nil {
		return x.OverviewPolyline
	}
	return nil
}

type DirectionsResponse_GeocodedWaypoint struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	GeocoderStatus string                 `protobuf:"bytes,1,opt,name=geocoder_status,json=geocoderStatus,proto3" json:"geocoder_status,omitempty"`
	PlaceId        string                 `protobuf:"bytes,2,opt,name=place_id,json=placeId,proto3" json:"place_id,omitempty"`
	Types          []string               `protobuf:"bytes,3,rep,name=types,proto3" json:"types,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *DirectionsResponse_GeocodedWaypoint) Reset() {
	*x = DirectionsResponse_GeocodedWaypoint{}
	mi := &file_maps_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DirectionsResponse_GeocodedWaypoint) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DirectionsResponse_GeocodedWaypoint) ProtoMessage() {}

func (x *DirectionsResponse_GeocodedWaypoint) ProtoReflect() protoreflect.Message {
	mi := &file_maps_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DirectionsResponse_GeocodedWaypoint.ProtoReflect.Descriptor instead.
func (*DirectionsResponse_GeocodedWaypoint) Descriptor() ([]byte, []int) {
	return file_maps_proto_rawDescGZIP(), []int{8, 6}
}

func (x *DirectionsResponse_GeocodedWaypoint) GetGeocoderStatus() string {
	if x != nil {
		return x.GeocoderStatus
	}
	return ""
}

func (x *DirectionsResponse_GeocodedWaypoint) GetPlaceId() string {
	if x != nil {
		return x.PlaceId
	}
	return ""
}

func (x *DirectionsResponse_GeocodedWaypoint) GetTypes() []string {
	if x != nil {
		return x.Types
	}
	return nil
}

type DistanceMatrixResponse_Element struct {
	state         protoimpl.MessageState                   `protogen:"open.v1"`
	Status        string                                   `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Duration      *DistanceMatrixResponse_Element_Duration `protobuf:"bytes,2,opt,name=duration,proto3" json:"duration,omitempty"`
	Distance      *DistanceMatrixResponse_Element_Distance `protobuf:"bytes,3,opt,name=distance,proto3" json:"distance,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DistanceMatrixResponse_Element) Reset() {
	*x = DistanceMatrixResponse_Element{}
	mi := &file_maps_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DistanceMatrixResponse_Element) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DistanceMatrixResponse_Element) ProtoMessage() {}

func (x *DistanceMatrixResponse_Element) ProtoReflect() protoreflect.Message {
	mi := &file_maps_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DistanceMatrixResponse_Element.ProtoReflect.Descriptor instead.
func (*DistanceMatrixResponse_Element) Descriptor() ([]byte, []int) {
	return file_maps_proto_rawDescGZIP(), []int{10, 0}
}

func (x *DistanceMatrixResponse_Element) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *DistanceMatrixResponse_Element) GetDuration() *DistanceMatrixResponse_Element_Duration {
	if x != nil {
		return x.Duration
	}
	return nil
}

func (x *DistanceMatrixResponse_Element) GetDistance() *DistanceMatrixResponse_Element_Distance {
	if x != nil {
		return x.Distance
	}
	return nil
}

type DistanceMatrixResponse_Row struct {
	state         protoimpl.MessageState            `protogen:"open.v1"`
	Elements      []*DistanceMatrixResponse_Element `protobuf:"bytes,1,rep,name=elements,proto3" json:"elements,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DistanceMatrixResponse_Row) Reset() {
	*x = DistanceMatrixResponse_Row{}
	mi := &file_maps_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DistanceMatrixResponse_Row) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DistanceMatrixResponse_Row) ProtoMessage() {}

func (x *DistanceMatrixResponse_Row) ProtoReflect() protoreflect.Message {
	mi := &file_maps_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DistanceMatrixResponse_Row.ProtoReflect.Descriptor instead.
func (*DistanceMatrixResponse_Row) Descriptor() ([]byte, []int) {
	return file_maps_proto_rawDescGZIP(), []int{10, 1}
}

func (x *DistanceMatrixResponse_Row) GetElements() []*DistanceMatrixResponse_Element {
	if x != nil {
		return x.Elements
	}
	return nil
}

type DistanceMatrixResponse_Element_Duration struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Text          string                 `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`
	Value         int32                  `protobuf:"varint,2,opt,name=value,proto3" json:"value,omitempty"` // seconds
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DistanceMatrixResponse_Element_Duration) Reset() {
	*x = DistanceMatrixResponse_Element_Duration{}
	mi := &file_maps_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DistanceMatrixResponse_Element_Duration) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DistanceMatrixResponse_Element_Duration) ProtoMessage() {}

func (x *DistanceMatrixResponse_Element_Duration) ProtoReflect() protoreflect.Message {
	mi := &file_maps_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DistanceMatrixResponse_Element_Duration.ProtoReflect.Descriptor instead.
func (*DistanceMatrixResponse_Element_Duration) Descriptor() ([]byte, []int) {
	return file_maps_proto_rawDescGZIP(), []int{10, 0, 0}
}

func (x *DistanceMatrixResponse_Element_Duration) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *DistanceMatrixResponse_Element_Duration) GetValue() int32 {
	if x != nil {
		return x.Value
	}
	return 0
}

type DistanceMatrixResponse_Element_Distance struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Text          string                 `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`
	Value         int32                  `protobuf:"varint,2,opt,name=value,proto3" json:"value,omitempty"` // meters
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DistanceMatrixResponse_Element_Distance) Reset() {
	*x = DistanceMatrixResponse_Element_Distance{}
	mi := &file_maps_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DistanceMatrixResponse_Element_Distance) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DistanceMatrixResponse_Element_Distance) ProtoMessage() {}

func (x *DistanceMatrixResponse_Element_Distance) ProtoReflect() protoreflect.Message {
	mi := &file_maps_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DistanceMatrixResponse_Element_Distance.ProtoReflect.Descriptor instead.
func (*DistanceMatrixResponse_Element_Distance) Descriptor() ([]byte, []int) {
	return file_maps_proto_rawDescGZIP(), []int{10, 0, 1}
}

func (x *DistanceMatrixResponse_Element_Distance) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *DistanceMatrixResponse_Element_Distance) GetValue() int32 {
	if x != nil {
		return x.Value
	}
	return 0
}

var File_maps_proto protoreflect.FileDescriptor

const file_maps_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"maps.proto\x12\n" +
	"maps_proto\"*\n" +
	"\x0eGeocodeRequest\x12\x18\n" +
	"\aaddress\x18\x01 \x01(\tR\aaddress\"\x90\x02\n" +
	"\x0fGeocodeResponse\x12<\n" +
	"\aresults\x18\x01 \x03(\v2\".maps_proto.GeocodeResponse.ResultR\aresults\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x1a.\n" +
	"\bLocation\x12\x10\n" +
	"\x03lat\x18\x01 \x01(\x01R\x03lat\x12\x10\n" +
	"\x03lng\x18\x02 \x01(\x01R\x03lng\x1aw\n" +
	"\x06Result\x12+\n" +
	"\x11formatted_address\x18\x01 \x01(\tR\x10formattedAddress\x12@\n" +
	"\blocation\x18\x02 \x01(\v2$.maps_proto.GeocodeResponse.LocationR\blocation\"G\n" +
	"\x13SearchPlacesRequest\x12\x14\n" +
	"\x05query\x18\x01 \x01(\tR\x05query\x12\x1a\n" +
	"\blocation\x18\x02 \x01(\tR\blocation\"\xc7\x04\n" +
	"\x05Place\x12\x19\n" +
	"\bplace_id\x18\x01 \x01(\tR\aplaceId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1a\n" +
	"\bvicinity\x18\x03 \x01(\tR\bvicinity\x12\x16\n" +
	"\x06rating\x18\x04 \x01(\x01R\x06rating\x12,\n" +
	"\x12user_ratings_total\x18\x05 \x01(\x05R\x10userRatingsTotal\x12G\n" +
	"\x11geometry_location\x18\x06 \x01(\v2\x1a.maps_proto.Place.LocationR\x10geometryLocation\x12C\n" +
	"\ropening_hours\x18\a \x01(\v2\x1e.maps_proto.Place.OpeningHoursR\fopeningHours\x12/\n" +
	"\x06photos\x18\b \x03(\v2\x17.maps_proto.Place.PhotoR\x06photos\x12\x1d\n" +
	"\n" +
	"photo_urls\x18\t \x03(\tR\tphotoUrls\x12\x14\n" +
	"\x05types\x18\n" +
	" \x03(\tR\x05types\x1a.\n" +
	"\bLocation\x12\x10\n" +
	"\x03lat\x18\x01 \x01(\x01R\x03lat\x12\x10\n" +
	"\x03lng\x18\x02 \x01(\x01R\x03lng\x1a)\n" +
	"\fOpeningHours\x12\x19\n" +
	"\bopen_now\x18\x01 \x01(\bR\aopenNow\x1a^\n" +
	"\x05Photo\x12'\n" +
	"\x0fphoto_reference\x18\x01 \x01(\tR\x0ephotoReference\x12\x16\n" +
	"\x06height\x18\x02 \x01(\x05R\x06height\x12\x14\n" +
	"\x05width\x18\x03 \x01(\x05R\x05width\"[\n" +
	"\x14SearchPlacesResponse\x12+\n" +
	"\aresults\x18\x01 \x03(\v2\x11.maps_proto.PlaceR\aresults\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\"0\n" +
	"\x13PlaceDetailsRequest\x12\x19\n" +
	"\bplace_id\x18\x01 \x01(\tR\aplaceId\"Y\n" +
	"\x14PlaceDetailsResponse\x12)\n" +
	"\x06result\x18\x01 \x01(\v2\x11.maps_proto.PlaceR\x06result\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\"M\n" +
	"\x11DirectionsRequest\x12\x16\n" +
	"\x06origin\x18\x01 \x01(\tR\x06origin\x12 \n" +
	"\vdestination\x18\x02 \x01(\tR\vdestination\"\x92\t\n" +
	"\x12DirectionsResponse\x12<\n" +
	"\x06routes\x18\x01 \x03(\v2$.maps_proto.DirectionsResponse.RouteR\x06routes\x12^\n" +
	"\x12geocoded_waypoints\x18\x02 \x03(\v2/.maps_proto.DirectionsResponse.GeocodedWaypointR\x11geocodedWaypoints\x12\x16\n" +
	"\x06status\x18\x03 \x01(\tR\x06status\x1a4\n" +
	"\bDistance\x12\x12\n" +
	"\x04text\x18\x01 \x01(\tR\x04text\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x05R\x05value\x1a4\n" +
	"\bDuration\x12\x12\n" +
	"\x04text\x18\x01 \x01(\tR\x04text\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x05R\x05value\x1a\"\n" +
	"\bPolyline\x12\x16\n" +
	"\x06points\x18\x01 \x01(\tR\x06points\x1a\x82\x02\n" +
	"\x04Step\x12+\n" +
	"\x11html_instructions\x18\x01 \x01(\tR\x10htmlInstructions\x12C\n" +
	"\bdistance\x18\x02 \x01(\v2'.maps_proto.DirectionsResponse.DistanceR\bdistance\x12C\n" +
	"\bduration\x18\x03 \x01(\v2'.maps_proto.DirectionsResponse.DurationR\bduration\x12C\n" +
	"\bpolyline\x18\x04 \x01(\v2'.maps_proto.DirectionsResponse.PolylineR\bpolyline\x1a\x90\x02\n" +
	"\x03Leg\x12C\n" +
	"\bdistance\x18\x01 \x01(\v2'.maps_proto.DirectionsResponse.DistanceR\bdistance\x12C\n" +
	"\bduration\x18\x02 \x01(\v2'.maps_proto.DirectionsResponse.DurationR\bduration\x12#\n" +
	"\rstart_address\x18\x03 \x01(\tR\fstartAddress\x12\x1f\n" +
	"\vend_address\x18\x04 \x01(\tR\n" +
	"endAddress\x129\n" +
	"\x05steps\x18\x05 \x03(\v2#.maps_proto.DirectionsResponse.StepR\x05steps\x1a\xaf\x01\n" +
	"\x05Route\x12\x18\n" +
	"\asummary\x18\x01 \x01(\tR\asummary\x126\n" +
	"\x04legs\x18\x02 \x03(\v2\".maps_proto.DirectionsResponse.LegR\x04legs\x12T\n" +
	"\x11overview_polyline\x18\x03 \x01(\v2'.maps_proto.DirectionsResponse.PolylineR\x10overviewPolyline\x1al\n" +
	"\x10GeocodedWaypoint\x12'\n" +
	"\x0fgeocoder_status\x18\x01 \x01(\tR\x0egeocoderStatus\x12\x19\n" +
	"\bplace_id\x18\x02 \x01(\tR\aplaceId\x12\x14\n" +
	"\x05types\x18\x03 \x03(\tR\x05types\"U\n" +
	"\x15DistanceMatrixRequest\x12\x18\n" +
	"\aorigins\x18\x01 \x01(\tR\aorigins\x12\"\n" +
	"\fdestinations\x18\x02 \x01(\tR\fdestinations\"\xcd\x04\n" +
	"\x16DistanceMatrixResponse\x12)\n" +
	"\x10origin_addresses\x18\x01 \x03(\tR\x0foriginAddresses\x123\n" +
	"\x15destination_addresses\x18\x02 \x03(\tR\x14destinationAddresses\x12:\n" +
	"\x04rows\x18\x03 \x03(\v2&.maps_proto.DistanceMatrixResponse.RowR\x04rows\x12\x16\n" +
	"\x06status\x18\x04 \x01(\tR\x06status\x1a\xaf\x02\n" +
	"\aElement\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12O\n" +
	"\bduration\x18\x02 \x01(\v23.maps_proto.DistanceMatrixResponse.Element.DurationR\bduration\x12O\n" +
	"\bdistance\x18\x03 \x01(\v23.maps_proto.DistanceMatrixResponse.Element.DistanceR\bdistance\x1a4\n" +
	"\bDuration\x12\x12\n" +
	"\x04text\x18\x01 \x01(\tR\x04text\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x05R\x05value\x1a4\n" +
	"\bDistance\x12\x12\n" +
	"\x04text\x18\x01 \x01(\tR\x04text\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x05R\x05value\x1aM\n" +
	"\x03Row\x12F\n" +
	"\belements\x18\x01 \x03(\v2*.maps_proto.DistanceMatrixResponse.ElementR\belements2\x9f\x03\n" +
	"\x04Maps\x12B\n" +
	"\aGeocode\x12\x1a.maps_proto.GeocodeRequest\x1a\x1b.maps_proto.GeocodeResponse\x12Q\n" +
	"\fSearchPlaces\x12\x1f.maps_proto.SearchPlacesRequest\x1a .maps_proto.SearchPlacesResponse\x12T\n" +
	"\x0fGetPlaceDetails\x12\x1f.maps_proto.PlaceDetailsRequest\x1a .maps_proto.PlaceDetailsResponse\x12N\n" +
	"\rGetDirections\x12\x1d.maps_proto.DirectionsRequest\x1a\x1e.maps_proto.DirectionsResponse\x12Z\n" +
	"\x11GetDistanceMatrix\x12!.maps_proto.DistanceMatrixRequest\x1a\".maps_proto.DistanceMatrixResponseBG\n" +
	")com.example.planning.grpc.apiservice.mapsP\x01Z\x18api-service/grpc/pb/mapsb\x06proto3"

var (
	file_maps_proto_rawDescOnce sync.Once
	file_maps_proto_rawDescData []byte
)

func file_maps_proto_rawDescGZIP() []byte {
	file_maps_proto_rawDescOnce.Do(func() {
		file_maps_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_maps_proto_rawDesc), len(file_maps_proto_rawDesc)))
	})
	return file_maps_proto_rawDescData
}

var file_maps_proto_msgTypes = make([]protoimpl.MessageInfo, 27)
var file_maps_proto_goTypes = []any{
	(*GeocodeRequest)(nil),                          // 0: maps_proto.GeocodeRequest
	(*GeocodeResponse)(nil),                         // 1: maps_proto.GeocodeResponse
	(*SearchPlacesRequest)(nil),                     // 2: maps_proto.SearchPlacesRequest
	(*Place)(nil),                                   // 3: maps_proto.Place
	(*SearchPlacesResponse)(nil),                    // 4: maps_proto.SearchPlacesResponse
	(*PlaceDetailsRequest)(nil),                     // 5: maps_proto.PlaceDetailsRequest
	(*PlaceDetailsResponse)(nil),                    // 6: maps_proto.PlaceDetailsResponse
	(*DirectionsRequest)(nil),                       // 7: maps_proto.DirectionsRequest
	(*DirectionsResponse)(nil),                      // 8: maps_proto.DirectionsResponse
	(*DistanceMatrixRequest)(nil),                   // 9: maps_proto.DistanceMatrixRequest
	(*DistanceMatrixResponse)(nil),                  // 10: maps_proto.DistanceMatrixResponse
	(*GeocodeResponse_Location)(nil),                // 11: maps_proto.GeocodeResponse.Location
	(*GeocodeResponse_Result)(nil),                  // 12: maps_proto.GeocodeResponse.Result
	(*Place_Location)(nil),                          // 13: maps_proto.Place.Location
	(*Place_OpeningHours)(nil),                      // 14: maps_proto.Place.OpeningHours
	(*Place_Photo)(nil),                             // 15: maps_proto.Place.Photo
	(*DirectionsResponse_Distance)(nil),             // 16: maps_proto.DirectionsResponse.Distance
	(*DirectionsResponse_Duration)(nil),             // 17: maps_proto.DirectionsResponse.Duration
	(*DirectionsResponse_Polyline)(nil),             // 18: maps_proto.DirectionsResponse.Polyline
	(*DirectionsResponse_Step)(nil),                 // 19: maps_proto.DirectionsResponse.Step
	(*DirectionsResponse_Leg)(nil),                  // 20: maps_proto.DirectionsResponse.Leg
	(*DirectionsResponse_Route)(nil),                // 21: maps_proto.DirectionsResponse.Route
	(*DirectionsResponse_GeocodedWaypoint)(nil),     // 22: maps_proto.DirectionsResponse.GeocodedWaypoint
	(*DistanceMatrixResponse_Element)(nil),          // 23: maps_proto.DistanceMatrixResponse.Element
	(*DistanceMatrixResponse_Row)(nil),              // 24: maps_proto.DistanceMatrixResponse.Row
	(*DistanceMatrixResponse_Element_Duration)(nil), // 25: maps_proto.DistanceMatrixResponse.Element.Duration
	(*DistanceMatrixResponse_Element_Distance)(nil), // 26: maps_proto.DistanceMatrixResponse.Element.Distance
}
var file_maps_proto_depIdxs = []int32{
	12, // 0: maps_proto.GeocodeResponse.results:type_name -> maps_proto.GeocodeResponse.Result
	13, // 1: maps_proto.Place.geometry_location:type_name -> maps_proto.Place.Location
	14, // 2: maps_proto.Place.opening_hours:type_name -> maps_proto.Place.OpeningHours
	15, // 3: maps_proto.Place.photos:type_name -> maps_proto.Place.Photo
	3,  // 4: maps_proto.SearchPlacesResponse.results:type_name -> maps_proto.Place
	3,  // 5: maps_proto.PlaceDetailsResponse.result:type_name -> maps_proto.Place
	21, // 6: maps_proto.DirectionsResponse.routes:type_name -> maps_proto.DirectionsResponse.Route
	22, // 7: maps_proto.DirectionsResponse.geocoded_waypoints:type_name -> maps_proto.DirectionsResponse.GeocodedWaypoint
	24, // 8: maps_proto.DistanceMatrixResponse.rows:type_name -> maps_proto.DistanceMatrixResponse.Row
	11, // 9: maps_proto.GeocodeResponse.Result.location:type_name -> maps_proto.GeocodeResponse.Location
	16, // 10: maps_proto.DirectionsResponse.Step.distance:type_name -> maps_proto.DirectionsResponse.Distance
	17, // 11: maps_proto.DirectionsResponse.Step.duration:type_name -> maps_proto.DirectionsResponse.Duration
	18, // 12: maps_proto.DirectionsResponse.Step.polyline:type_name -> maps_proto.DirectionsResponse.Polyline
	16, // 13: maps_proto.DirectionsResponse.Leg.distance:type_name -> maps_proto.DirectionsResponse.Distance
	17, // 14: maps_proto.DirectionsResponse.Leg.duration:type_name -> maps_proto.DirectionsResponse.Duration
	19, // 15: maps_proto.DirectionsResponse.Leg.steps:type_name -> maps_proto.DirectionsResponse.Step
	20, // 16: maps_proto.DirectionsResponse.Route.legs:type_name -> maps_proto.DirectionsResponse.Leg
	18, // 17: maps_proto.DirectionsResponse.Route.overview_polyline:type_name -> maps_proto.DirectionsResponse.Polyline
	25, // 18: maps_proto.DistanceMatrixResponse.Element.duration:type_name -> maps_proto.DistanceMatrixResponse.Element.Duration
	26, // 19: maps_proto.DistanceMatrixResponse.Element.distance:type_name -> maps_proto.DistanceMatrixResponse.Element.Distance
	23, // 20: maps_proto.DistanceMatrixResponse.Row.elements:type_name -> maps_proto.DistanceMatrixResponse.Element
	0,  // 21: maps_proto.Maps.Geocode:input_type -> maps_proto.GeocodeRequest
	2,  // 22: maps_proto.Maps.SearchPlaces:input_type -> maps_proto.SearchPlacesRequest
	5,  // 23: maps_proto.Maps.GetPlaceDetails:input_type -> maps_proto.PlaceDetailsRequest
	7,  // 24: maps_proto.Maps.GetDirections:input_type -> maps_proto.DirectionsRequest
	9,  // 25: maps_proto.Maps.GetDistanceMatrix:input_type -> maps_proto.DistanceMatrixRequest
	1,  // 26: maps_proto.Maps.Geocode:output_type -> maps_proto.GeocodeResponse
	4,  // 27: maps_proto.Maps.SearchPlaces:output_type -> maps_proto.SearchPlacesResponse
	6,  // 28: maps_proto.Maps.GetPlaceDetails:output_type -> maps_proto.PlaceDetailsResponse
	8,  // 29: maps_proto.Maps.GetDirections:output_type -> maps_proto.DirectionsResponse
	10, // 30: maps_proto.Maps.GetDistanceMatrix:output_type -> maps_proto.DistanceMatrixResponse
	26, // [26:31] is the sub-list for method output_type
	21, // [21:26] is the sub-list for method input_type
	21, // [21:21] is the sub-list for extension type_name
	21, // [21:21] is the sub-list for extension extendee
	0,  // [0:21] is the sub-list for field type_name
}

func init() { file_maps_proto_init() }
func file_maps_proto_init() {
	if File_maps_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_maps_proto_rawDesc), len(file_maps_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   27,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_maps_proto_goTypes,
		DependencyIndexes: file_maps_proto_depIdxs,
		MessageInfos:      file_maps_proto_msgTypes,
	}.Build()
	File_maps_proto = out.File
	file_maps_proto_goTypes = nil
	file_maps_proto_depIdxs = nil
}
