// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.21.12
// source: maps.proto

package maps

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Maps_Geocode_FullMethodName           = "/maps_proto.Maps/Geocode"
	Maps_SearchPlaces_FullMethodName      = "/maps_proto.Maps/SearchPlaces"
	Maps_GetPlaceDetails_FullMethodName   = "/maps_proto.Maps/GetPlaceDetails"
	Maps_GetDirections_FullMethodName     = "/maps_proto.Maps/GetDirections"
	Maps_GetDistanceMatrix_FullMethodName = "/maps_proto.Maps/GetDistanceMatrix"
)

// MapsClient is the client API for Maps service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Maps Service
type MapsClient interface {
	Geocode(ctx context.Context, in *GeocodeRequest, opts ...grpc.CallOption) (*GeocodeResponse, error)
	SearchPlaces(ctx context.Context, in *SearchPlacesRequest, opts ...grpc.CallOption) (*SearchPlacesResponse, error)
	GetPlaceDetails(ctx context.Context, in *PlaceDetailsRequest, opts ...grpc.CallOption) (*PlaceDetailsResponse, error)
	GetDirections(ctx context.Context, in *DirectionsRequest, opts ...grpc.CallOption) (*DirectionsResponse, error)
	GetDistanceMatrix(ctx context.Context, in *DistanceMatrixRequest, opts ...grpc.CallOption) (*DistanceMatrixResponse, error)
}

type mapsClient struct {
	cc grpc.ClientConnInterface
}

func NewMapsClient(cc grpc.ClientConnInterface) MapsClient {
	return &mapsClient{cc}
}

func (c *mapsClient) Geocode(ctx context.Context, in *GeocodeRequest, opts ...grpc.CallOption) (*GeocodeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GeocodeResponse)
	err := c.cc.Invoke(ctx, Maps_Geocode_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mapsClient) SearchPlaces(ctx context.Context, in *SearchPlacesRequest, opts ...grpc.CallOption) (*SearchPlacesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SearchPlacesResponse)
	err := c.cc.Invoke(ctx, Maps_SearchPlaces_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mapsClient) GetPlaceDetails(ctx context.Context, in *PlaceDetailsRequest, opts ...grpc.CallOption) (*PlaceDetailsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PlaceDetailsResponse)
	err := c.cc.Invoke(ctx, Maps_GetPlaceDetails_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mapsClient) GetDirections(ctx context.Context, in *DirectionsRequest, opts ...grpc.CallOption) (*DirectionsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DirectionsResponse)
	err := c.cc.Invoke(ctx, Maps_GetDirections_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mapsClient) GetDistanceMatrix(ctx context.Context, in *DistanceMatrixRequest, opts ...grpc.CallOption) (*DistanceMatrixResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DistanceMatrixResponse)
	err := c.cc.Invoke(ctx, Maps_GetDistanceMatrix_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MapsServer is the server API for Maps service.
// All implementations must embed UnimplementedMapsServer
// for forward compatibility.
//
// Maps Service
type MapsServer interface {
	Geocode(context.Context, *GeocodeRequest) (*GeocodeResponse, error)
	SearchPlaces(context.Context, *SearchPlacesRequest) (*SearchPlacesResponse, error)
	GetPlaceDetails(context.Context, *PlaceDetailsRequest) (*PlaceDetailsResponse, error)
	GetDirections(context.Context, *DirectionsRequest) (*DirectionsResponse, error)
	GetDistanceMatrix(context.Context, *DistanceMatrixRequest) (*DistanceMatrixResponse, error)
	mustEmbedUnimplementedMapsServer()
}

// UnimplementedMapsServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedMapsServer struct{}

func (UnimplementedMapsServer) Geocode(context.Context, *GeocodeRequest) (*GeocodeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Geocode not implemented")
}
func (UnimplementedMapsServer) SearchPlaces(context.Context, *SearchPlacesRequest) (*SearchPlacesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SearchPlaces not implemented")
}
func (UnimplementedMapsServer) GetPlaceDetails(context.Context, *PlaceDetailsRequest) (*PlaceDetailsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetPlaceDetails not implemented")
}
func (UnimplementedMapsServer) GetDirections(context.Context, *DirectionsRequest) (*DirectionsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetDirections not implemented")
}
func (UnimplementedMapsServer) GetDistanceMatrix(context.Context, *DistanceMatrixRequest) (*DistanceMatrixResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetDistanceMatrix not implemented")
}
func (UnimplementedMapsServer) mustEmbedUnimplementedMapsServer() {}
func (UnimplementedMapsServer) testEmbeddedByValue()              {}

// UnsafeMapsServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MapsServer will
// result in compilation errors.
type UnsafeMapsServer interface {
	mustEmbedUnimplementedMapsServer()
}

func RegisterMapsServer(s grpc.ServiceRegistrar, srv MapsServer) {
	// If the following call pancis, it indicates UnimplementedMapsServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Maps_ServiceDesc, srv)
}

func _Maps_Geocode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GeocodeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MapsServer).Geocode(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Maps_Geocode_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MapsServer).Geocode(ctx, req.(*GeocodeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Maps_SearchPlaces_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SearchPlacesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MapsServer).SearchPlaces(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Maps_SearchPlaces_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MapsServer).SearchPlaces(ctx, req.(*SearchPlacesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Maps_GetPlaceDetails_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PlaceDetailsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MapsServer).GetPlaceDetails(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Maps_GetPlaceDetails_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MapsServer).GetPlaceDetails(ctx, req.(*PlaceDetailsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Maps_GetDirections_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DirectionsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MapsServer).GetDirections(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Maps_GetDirections_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MapsServer).GetDirections(ctx, req.(*DirectionsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Maps_GetDistanceMatrix_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DistanceMatrixRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MapsServer).GetDistanceMatrix(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Maps_GetDistanceMatrix_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MapsServer).GetDistanceMatrix(ctx, req.(*DistanceMatrixRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Maps_ServiceDesc is the grpc.ServiceDesc for Maps service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Maps_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "maps_proto.Maps",
	HandlerType: (*MapsServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Geocode",
			Handler:    _Maps_Geocode_Handler,
		},
		{
			MethodName: "SearchPlaces",
			Handler:    _Maps_SearchPlaces_Handler,
		},
		{
			MethodName: "GetPlaceDetails",
			Handler:    _Maps_GetPlaceDetails_Handler,
		},
		{
			MethodName: "GetDirections",
			Handler:    _Maps_GetDirections_Handler,
		},
		{
			MethodName: "GetDistanceMatrix",
			Handler:    _Maps_GetDistanceMatrix_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "maps.proto",
}
