// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.21.12
// source: gemini.proto

package gemini

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Gemini_GenerateContent_FullMethodName = "/gemini_proto.Gemini/GenerateContent"
)

// GeminiClient is the client API for Gemini service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Gemini Service
type GeminiClient interface {
	GenerateContent(ctx context.Context, in *GeminiRequest, opts ...grpc.CallOption) (*GeminiResponse, error)
}

type geminiClient struct {
	cc grpc.ClientConnInterface
}

func NewGeminiClient(cc grpc.ClientConnInterface) GeminiClient {
	return &geminiClient{cc}
}

func (c *geminiClient) GenerateContent(ctx context.Context, in *GeminiRequest, opts ...grpc.CallOption) (*GeminiResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GeminiResponse)
	err := c.cc.Invoke(ctx, Gemini_GenerateContent_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GeminiServer is the server API for Gemini service.
// All implementations must embed UnimplementedGeminiServer
// for forward compatibility.
//
// Gemini Service
type GeminiServer interface {
	GenerateContent(context.Context, *GeminiRequest) (*GeminiResponse, error)
	mustEmbedUnimplementedGeminiServer()
}

// UnimplementedGeminiServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedGeminiServer struct{}

func (UnimplementedGeminiServer) GenerateContent(context.Context, *GeminiRequest) (*GeminiResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GenerateContent not implemented")
}
func (UnimplementedGeminiServer) mustEmbedUnimplementedGeminiServer() {}
func (UnimplementedGeminiServer) testEmbeddedByValue()                {}

// UnsafeGeminiServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to GeminiServer will
// result in compilation errors.
type UnsafeGeminiServer interface {
	mustEmbedUnimplementedGeminiServer()
}

func RegisterGeminiServer(s grpc.ServiceRegistrar, srv GeminiServer) {
	// If the following call pancis, it indicates UnimplementedGeminiServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Gemini_ServiceDesc, srv)
}

func _Gemini_GenerateContent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GeminiRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GeminiServer).GenerateContent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Gemini_GenerateContent_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GeminiServer).GenerateContent(ctx, req.(*GeminiRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Gemini_ServiceDesc is the grpc.ServiceDesc for Gemini service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Gemini_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "gemini_proto.Gemini",
	HandlerType: (*GeminiServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GenerateContent",
			Handler:    _Gemini_GenerateContent_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "gemini.proto",
}
