// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.21.12
// source: gemini.proto

package gemini

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GeminiRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Prompt        string                 `protobuf:"bytes,1,opt,name=prompt,proto3" json:"prompt,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GeminiRequest) Reset() {
	*x = GeminiRequest{}
	mi := &file_gemini_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GeminiRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GeminiRequest) ProtoMessage() {}

func (x *GeminiRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gemini_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GeminiRequest.ProtoReflect.Descriptor instead.
func (*GeminiRequest) Descriptor() ([]byte, []int) {
	return file_gemini_proto_rawDescGZIP(), []int{0}
}

func (x *GeminiRequest) GetPrompt() string {
	if x != nil {
		return x.Prompt
	}
	return ""
}

type GeminiResponse struct {
	state          protoimpl.MessageState         `protogen:"open.v1"`
	Candidates     []*GeminiResponse_Candidate    `protobuf:"bytes,1,rep,name=candidates,proto3" json:"candidates,omitempty"`
	PromptFeedback *GeminiResponse_PromptFeedback `protobuf:"bytes,2,opt,name=prompt_feedback,json=promptFeedback,proto3" json:"prompt_feedback,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *GeminiResponse) Reset() {
	*x = GeminiResponse{}
	mi := &file_gemini_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GeminiResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GeminiResponse) ProtoMessage() {}

func (x *GeminiResponse) ProtoReflect() protoreflect.Message {
	mi := &file_gemini_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GeminiResponse.ProtoReflect.Descriptor instead.
func (*GeminiResponse) Descriptor() ([]byte, []int) {
	return file_gemini_proto_rawDescGZIP(), []int{1}
}

func (x *GeminiResponse) GetCandidates() []*GeminiResponse_Candidate {
	if x != nil {
		return x.Candidates
	}
	return nil
}

func (x *GeminiResponse) GetPromptFeedback() *GeminiResponse_PromptFeedback {
	if x != nil {
		return x.PromptFeedback
	}
	return nil
}

type GeminiResponse_SafetyRating struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Category      string                 `protobuf:"bytes,1,opt,name=category,proto3" json:"category,omitempty"`
	Probability   string                 `protobuf:"bytes,2,opt,name=probability,proto3" json:"probability,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GeminiResponse_SafetyRating) Reset() {
	*x = GeminiResponse_SafetyRating{}
	mi := &file_gemini_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GeminiResponse_SafetyRating) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GeminiResponse_SafetyRating) ProtoMessage() {}

func (x *GeminiResponse_SafetyRating) ProtoReflect() protoreflect.Message {
	mi := &file_gemini_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GeminiResponse_SafetyRating.ProtoReflect.Descriptor instead.
func (*GeminiResponse_SafetyRating) Descriptor() ([]byte, []int) {
	return file_gemini_proto_rawDescGZIP(), []int{1, 0}
}

func (x *GeminiResponse_SafetyRating) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

func (x *GeminiResponse_SafetyRating) GetProbability() string {
	if x != nil {
		return x.Probability
	}
	return ""
}

type GeminiResponse_ContentPart struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Text          string                 `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GeminiResponse_ContentPart) Reset() {
	*x = GeminiResponse_ContentPart{}
	mi := &file_gemini_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GeminiResponse_ContentPart) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GeminiResponse_ContentPart) ProtoMessage() {}

func (x *GeminiResponse_ContentPart) ProtoReflect() protoreflect.Message {
	mi := &file_gemini_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GeminiResponse_ContentPart.ProtoReflect.Descriptor instead.
func (*GeminiResponse_ContentPart) Descriptor() ([]byte, []int) {
	return file_gemini_proto_rawDescGZIP(), []int{1, 1}
}

func (x *GeminiResponse_ContentPart) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

type GeminiResponse_Content struct {
	state         protoimpl.MessageState        `protogen:"open.v1"`
	Parts         []*GeminiResponse_ContentPart `protobuf:"bytes,1,rep,name=parts,proto3" json:"parts,omitempty"`
	Role          string                        `protobuf:"bytes,2,opt,name=role,proto3" json:"role,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GeminiResponse_Content) Reset() {
	*x = GeminiResponse_Content{}
	mi := &file_gemini_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GeminiResponse_Content) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GeminiResponse_Content) ProtoMessage() {}

func (x *GeminiResponse_Content) ProtoReflect() protoreflect.Message {
	mi := &file_gemini_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GeminiResponse_Content.ProtoReflect.Descriptor instead.
func (*GeminiResponse_Content) Descriptor() ([]byte, []int) {
	return file_gemini_proto_rawDescGZIP(), []int{1, 2}
}

func (x *GeminiResponse_Content) GetParts() []*GeminiResponse_ContentPart {
	if x != nil {
		return x.Parts
	}
	return nil
}

func (x *GeminiResponse_Content) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

type GeminiResponse_Candidate struct {
	state         protoimpl.MessageState         `protogen:"open.v1"`
	Content       *GeminiResponse_Content        `protobuf:"bytes,1,opt,name=content,proto3" json:"content,omitempty"`
	FinishReason  string                         `protobuf:"bytes,2,opt,name=finish_reason,json=finishReason,proto3" json:"finish_reason,omitempty"`
	Index         int32                          `protobuf:"varint,3,opt,name=index,proto3" json:"index,omitempty"`
	SafetyRatings []*GeminiResponse_SafetyRating `protobuf:"bytes,4,rep,name=safety_ratings,json=safetyRatings,proto3" json:"safety_ratings,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GeminiResponse_Candidate) Reset() {
	*x = GeminiResponse_Candidate{}
	mi := &file_gemini_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GeminiResponse_Candidate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GeminiResponse_Candidate) ProtoMessage() {}

func (x *GeminiResponse_Candidate) ProtoReflect() protoreflect.Message {
	mi := &file_gemini_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GeminiResponse_Candidate.ProtoReflect.Descriptor instead.
func (*GeminiResponse_Candidate) Descriptor() ([]byte, []int) {
	return file_gemini_proto_rawDescGZIP(), []int{1, 3}
}

func (x *GeminiResponse_Candidate) GetContent() *GeminiResponse_Content {
	if x != nil {
		return x.Content
	}
	return nil
}

func (x *GeminiResponse_Candidate) GetFinishReason() string {
	if x != nil {
		return x.FinishReason
	}
	return ""
}

func (x *GeminiResponse_Candidate) GetIndex() int32 {
	if x != nil {
		return x.Index
	}
	return 0
}

func (x *GeminiResponse_Candidate) GetSafetyRatings() []*GeminiResponse_SafetyRating {
	if x != nil {
		return x.SafetyRatings
	}
	return nil
}

type GeminiResponse_PromptFeedback struct {
	state         protoimpl.MessageState         `protogen:"open.v1"`
	SafetyRatings []*GeminiResponse_SafetyRating `protobuf:"bytes,2,rep,name=safety_ratings,json=safetyRatings,proto3" json:"safety_ratings,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GeminiResponse_PromptFeedback) Reset() {
	*x = GeminiResponse_PromptFeedback{}
	mi := &file_gemini_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GeminiResponse_PromptFeedback) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GeminiResponse_PromptFeedback) ProtoMessage() {}

func (x *GeminiResponse_PromptFeedback) ProtoReflect() protoreflect.Message {
	mi := &file_gemini_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GeminiResponse_PromptFeedback.ProtoReflect.Descriptor instead.
func (*GeminiResponse_PromptFeedback) Descriptor() ([]byte, []int) {
	return file_gemini_proto_rawDescGZIP(), []int{1, 4}
}

func (x *GeminiResponse_PromptFeedback) GetSafetyRatings() []*GeminiResponse_SafetyRating {
	if x != nil {
		return x.SafetyRatings
	}
	return nil
}

var File_gemini_proto protoreflect.FileDescriptor

const file_gemini_proto_rawDesc = "" +
	"\n" +
	"\fgemini.proto\x12\fgemini_proto\"'\n" +
	"\rGeminiRequest\x12\x16\n" +
	"\x06prompt\x18\x01 \x01(\tR\x06prompt\"\xbd\x05\n" +
	"\x0eGeminiResponse\x12F\n" +
	"\n" +
	"candidates\x18\x01 \x03(\v2&.gemini_proto.GeminiResponse.CandidateR\n" +
	"candidates\x12T\n" +
	"\x0fprompt_feedback\x18\x02 \x01(\v2+.gemini_proto.GeminiResponse.PromptFeedbackR\x0epromptFeedback\x1aL\n" +
	"\fSafetyRating\x12\x1a\n" +
	"\bcategory\x18\x01 \x01(\tR\bcategory\x12 \n" +
	"\vprobability\x18\x02 \x01(\tR\vprobability\x1a!\n" +
	"\vContentPart\x12\x12\n" +
	"\x04text\x18\x01 \x01(\tR\x04text\x1a]\n" +
	"\aContent\x12>\n" +
	"\x05parts\x18\x01 \x03(\v2(.gemini_proto.GeminiResponse.ContentPartR\x05parts\x12\x12\n" +
	"\x04role\x18\x02 \x01(\tR\x04role\x1a\xd8\x01\n" +
	"\tCandidate\x12>\n" +
	"\acontent\x18\x01 \x01(\v2$.gemini_proto.GeminiResponse.ContentR\acontent\x12#\n" +
	"\rfinish_reason\x18\x02 \x01(\tR\ffinishReason\x12\x14\n" +
	"\x05index\x18\x03 \x01(\x05R\x05index\x12P\n" +
	"\x0esafety_ratings\x18\x04 \x03(\v2).gemini_proto.GeminiResponse.SafetyRatingR\rsafetyRatings\x1ab\n" +
	"\x0ePromptFeedback\x12P\n" +
	"\x0esafety_ratings\x18\x02 \x03(\v2).gemini_proto.GeminiResponse.SafetyRatingR\rsafetyRatings2V\n" +
	"\x06Gemini\x12L\n" +
	"\x0fGenerateContent\x12\x1b.gemini_proto.GeminiRequest\x1a\x1c.gemini_proto.GeminiResponseBK\n" +
	"+com.example.planning.grpc.apiservice.geminiP\x01Z\x1aapi-service/grpc/pb/geminib\x06proto3"

var (
	file_gemini_proto_rawDescOnce sync.Once
	file_gemini_proto_rawDescData []byte
)

func file_gemini_proto_rawDescGZIP() []byte {
	file_gemini_proto_rawDescOnce.Do(func() {
		file_gemini_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_gemini_proto_rawDesc), len(file_gemini_proto_rawDesc)))
	})
	return file_gemini_proto_rawDescData
}

var file_gemini_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_gemini_proto_goTypes = []any{
	(*GeminiRequest)(nil),                 // 0: gemini_proto.GeminiRequest
	(*GeminiResponse)(nil),                // 1: gemini_proto.GeminiResponse
	(*GeminiResponse_SafetyRating)(nil),   // 2: gemini_proto.GeminiResponse.SafetyRating
	(*GeminiResponse_ContentPart)(nil),    // 3: gemini_proto.GeminiResponse.ContentPart
	(*GeminiResponse_Content)(nil),        // 4: gemini_proto.GeminiResponse.Content
	(*GeminiResponse_Candidate)(nil),      // 5: gemini_proto.GeminiResponse.Candidate
	(*GeminiResponse_PromptFeedback)(nil), // 6: gemini_proto.GeminiResponse.PromptFeedback
}
var file_gemini_proto_depIdxs = []int32{
	5, // 0: gemini_proto.GeminiResponse.candidates:type_name -> gemini_proto.GeminiResponse.Candidate
	6, // 1: gemini_proto.GeminiResponse.prompt_feedback:type_name -> gemini_proto.GeminiResponse.PromptFeedback
	3, // 2: gemini_proto.GeminiResponse.Content.parts:type_name -> gemini_proto.GeminiResponse.ContentPart
	4, // 3: gemini_proto.GeminiResponse.Candidate.content:type_name -> gemini_proto.GeminiResponse.Content
	2, // 4: gemini_proto.GeminiResponse.Candidate.safety_ratings:type_name -> gemini_proto.GeminiResponse.SafetyRating
	2, // 5: gemini_proto.GeminiResponse.PromptFeedback.safety_ratings:type_name -> gemini_proto.GeminiResponse.SafetyRating
	0, // 6: gemini_proto.Gemini.GenerateContent:input_type -> gemini_proto.GeminiRequest
	1, // 7: gemini_proto.Gemini.GenerateContent:output_type -> gemini_proto.GeminiResponse
	7, // [7:8] is the sub-list for method output_type
	6, // [6:7] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_gemini_proto_init() }
func file_gemini_proto_init() {
	if File_gemini_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_gemini_proto_rawDesc), len(file_gemini_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_gemini_proto_goTypes,
		DependencyIndexes: file_gemini_proto_depIdxs,
		MessageInfos:      file_gemini_proto_msgTypes,
	}.Build()
	File_gemini_proto = out.File
	file_gemini_proto_goTypes = nil
	file_gemini_proto_depIdxs = nil
}
